FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["/src/Elf.Web/Elf.Web.csproj", "Elf.Web/"]
COPY ["/src/Elf.Services/Elf.Services.csproj", "Elf.Services/"]
RUN dotnet restore "Elf.Web/Elf.Web.csproj"
COPY ./src .
WORKDIR "/src/Elf.Web"
RUN dotnet build "Elf.Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Elf.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Elf.Web.dll"]