SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Link](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OriginUrl] [nvarchar](256) NULL,
	[FwToken] [varchar](32) NULL,
	[Note] [nvarchar](max) NULL,
	[IsEnabled] [bit] NOT NULL,
	[UpdateTimeUtc] [datetime] NOT NULL,
	[AkaName] [varchar](32) NULL,
	[TTL] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LinkTag](
	[LinkId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_LinkTag] PRIMARY KEY CLUSTERED 
(
	[LinkId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LinkTracking](
	[Id] [uniqueidentifier] NOT NULL,
	[LinkId] [int] NOT NULL,
	[UserAgent] [nvarchar](256) NULL,
	[IpAddress] [varchar](64) NULL,
	[RequestTimeUtc] [datetime] NOT NULL,
	[IPCountry] [nvarchar](64) NULL,
	[IPRegion] [nvarchar](64) NULL,
	[IPCity] [nvarchar](64) NULL,
	[IPASN] [varchar](16) NULL,
	[IPOrg] [varchar](64) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LinkTag]  WITH CHECK ADD  CONSTRAINT [FK_LinkTag_Link] FOREIGN KEY([LinkId])
REFERENCES [dbo].[Link] ([Id])
GO
ALTER TABLE [dbo].[LinkTag] CHECK CONSTRAINT [FK_LinkTag_Link]
GO
ALTER TABLE [dbo].[LinkTag]  WITH CHECK ADD  CONSTRAINT [FK_LinkTag_Tag] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
GO
ALTER TABLE [dbo].[LinkTag] CHECK CONSTRAINT [FK_LinkTag_Tag]
GO
ALTER TABLE [dbo].[LinkTracking]  WITH CHECK ADD  CONSTRAINT [FK_LinkTracking_Link] FOREIGN KEY([LinkId])
REFERENCES [dbo].[Link] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[LinkTracking] CHECK CONSTRAINT [FK_LinkTracking_Link]
GO
