CREATE TABLE "Link" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "OriginUrl" character varying(256) NULL,
    "FwToken" character varying(32) NULL,
    "Note" text NULL,
    "IsEnabled" boolean NOT NULL,
    "UpdateTimeUtc" timestamp with time zone NOT NULL,
    "AkaName" character varying(32) NULL,
    "TTL" integer NULL,
    CONSTRAINT "PK_Link" PRIMARY KEY ("Id")
);

CREATE TABLE "Tag" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" character varying(32) NOT NULL,
    CONSTRAINT "PK_Tag" PRIMARY KEY ("Id")
);

CREATE TABLE "LinkTag" (
    "LinkId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_LinkTag" PRIMARY KEY ("LinkId", "TagId")
);

CREATE TABLE "LinkTracking" (
    "Id" uuid NOT NULL,
    "LinkId" integer NOT NULL,
    "UserAgent" character varying(256) NULL,
    "IpAddress" character varying(64) NULL,
    "RequestTimeUtc" timestamp with time zone NOT NULL,
    "IPCountry" character varying(64) NULL,
    "IPRegion" character varying(64) NULL,
    "IPCity" character varying(64) NULL,
    "IPASN" character varying(16) NULL,
    "IPOrg" character varying(64) NULL,
    CONSTRAINT "PK_LinkTracking" PRIMARY KEY ("Id")
);

CREATE TABLE "ElfConfiguration" (
    "CfgKey" character varying(64) NOT NULL,
    "CfgValue" text NULL,
    "LastModifiedTimeUtc" timestamp with time zone NULL,
    CONSTRAINT "PK_ElfConfiguration_CfgKey" PRIMARY KEY ("CfgKey")
);

CREATE UNIQUE INDEX "IX_Link_FwToken"
ON "Link" ("FwToken" ASC)
WHERE "FwToken" IS NOT NULL;

CREATE UNIQUE INDEX "IX_Link_AkaName"
ON "Link" ("AkaName" ASC)
WHERE "AkaName" IS NOT NULL;

CREATE INDEX "IX_Link_UpdateTimeUtc"
ON "Link" ("UpdateTimeUtc" DESC);

CREATE INDEX "IX_LinkTracking_LinkId_RequestTimeUtc"
ON "LinkTracking" ("LinkId" ASC, "RequestTimeUtc" DESC);

CREATE INDEX "IX_LinkTracking_RequestTimeUtc"
ON "LinkTracking" ("RequestTimeUtc" DESC);

CREATE UNIQUE INDEX "IX_Tag_Name"
ON "Tag" ("Name" ASC);

ALTER TABLE "LinkTag"
ADD CONSTRAINT "FK_LinkTag_Link" FOREIGN KEY ("LinkId")
REFERENCES "Link" ("Id");

ALTER TABLE "LinkTag"
ADD CONSTRAINT "FK_LinkTag_Tag" FOREIGN KEY ("TagId")
REFERENCES "Tag" ("Id");

ALTER TABLE "LinkTracking"
ADD CONSTRAINT "FK_LinkTracking_Link" FOREIGN KEY ("LinkId")
REFERENCES "Link" ("Id")
ON UPDATE CASCADE
ON DELETE CASCADE;
