<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Setup\SQL\schema.sql" />
      <None Remove="Setup\SQL\schema.postgresql.sql" />
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="System.Text" />
        <Using Include="Microsoft.AspNetCore.Mvc" />
        <Using Include="Microsoft.AspNetCore.Builder" />
        <Using Include="Microsoft.AspNetCore.Http" />
        <Using Include="Microsoft.Extensions.Configuration" />
        <Using Include="Microsoft.Extensions.DependencyInjection" />
        <Using Include="Microsoft.Extensions.Hosting" />
        <Using Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LiteBus" Version="6.0.2" />
		<PackageReference Include="LiteBus.Extensions.Microsoft.DependencyInjection" Version="6.0.2" />
        <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="4.7.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Elf.Data\Elf.Data.csproj" />
        <ProjectReference Include="..\Elf.Shared\Elf.Shared.csproj" />
        <ProjectReference Include="..\Elf.TokenGenerator\Elf.TokenGenerator.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Setup\SQL\schema.sql" />
      <EmbeddedResource Include="Setup\SQL\schema.postgresql.sql" />
    </ItemGroup>

</Project>
