<Project>
  <PropertyGroup>
    <Authors>Edi Wang</Authors>
    <Company>edi.wang</Company>
    <Copyright>(C) 2026 edi.wang@outlook.com</Copyright>
    <AssemblyVersion>10.0.0.0</AssemblyVersion>
    <FileVersion>10.0.0.0</FileVersion>
    <Version>10.0.0-beta.1</Version>
  </PropertyGroup>
</Project>
