name: ACR Build and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag elf:latest
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: ACR Build and Publish
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.ACR_SERVER }}/elf:latest
        docker tag ${{ secrets.ACR_SERVER }}/elf:latest ${{ secrets.ACR_SERVER }}/azureregistrygitactions:$(date +%s)
        docker push ${{ secrets.ACR_SERVER }}/elf
