name: Forwarder API (Docker)

on:
  push:
    branches: [ master ]
    paths: [ src/** ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./src
        file: ./src/Elf.Api/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/elf:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
