name: Docker for API

on:
  push:
    branches: [ master ]
    paths: [ src/API/** ]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/API
        file: ./src/API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/elf:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}