name: Docker for Admin

on:
  push:
    branches: [ master ]
    paths: [ src/Admin/** ]
jobs:


  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: ./src/Admin/elf-admin
        file: ./src/Admin/elf-admin/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/elf-admin:latest
        # build-args: |
        #   "KENDO_UI_LICENSE=${{ secrets.KENDO_UI_LICENSE }}"

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
